# Generated by Django 4.0.2 on 2022-03-08 22:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=ckeditor.fields.RichTextField(help_text='文章简介', max_length=500),
        ),
    ]
