# Generated by Django 3.2.12 on 2022-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blogdetailpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(help_text='文章简介', max_length=500, verbose_name='Introduction'),
        ),
    ]
