# Generated by Django 3.2.12 on 2022-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogdetailpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='collection',
            field=models.CharField(blank=True, max_length=10, verbose_name='collection'),
        ),
    ]
