# Generated by Django 3.2.12 on 2022-05-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_blogdetailpage_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='文章标题', max_length=80, verbose_name='Title'),
        ),
    ]
