# Generated by Django 3.2.12 on 2022-05-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blogdetailpage_custom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='custom_title',
            field=models.CharField(help_text='文章标题', max_length=60, verbose_name='Title'),
        ),
    ]
