# Generated by Django 4.0.7 on 2022-09-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='count_visited',
            field=models.IntegerField(default=0),
        ),
    ]
