# Generated by Django 4.0.7 on 2022-09-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_blogdetailpage_count_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='count_visited',
        ),
    ]
