# Generated by Django 3.2.12 on 2022-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='location',
            field=models.CharField(default='', max_length=60, verbose_name='地理位置'),
            preserve_default=False,
        ),
    ]
