# Generated by Django 3.2.12 on 2022-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_record', '0002_userip_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.CharField(max_length=60, verbose_name='IP地址'),
        ),
    ]
