# Generated by Django 3.2.12 on 2022-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='icon',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
