# Generated by Django 3.2.12 on 2022-05-01 04:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
