# Generated by Django 3.2.12 on 2022-05-02 19:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('comment', '0002_alter_comment_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='MyComment',
        ),
    ]
