# Generated by Django 4.0.4 on 2022-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_rename_comment_mycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomment',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
