# Generated by Django 4.0.4 on 2022-05-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_mycomment_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycomment',
            options={'ordering': ['-update_time']},
        ),
    ]
